server:
  port: 8001

#mybatis配置
mybatis:
  type-aliases-package: com.whoami.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


#spring配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource #数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
    url: jdbc:mysql://101.43.118.204:3306/DB01?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: yxl123520.

